appBaseUrl: 'https://webstore.softserv.cloud'
clientId: $CLIENT_ID
clientSecret: $CLIENT_SECRET
nextAuthSecret: $NEXTAUTH_SECRET
nextAuthUrl: 'https://webstore.softserv.cloud/api/auth'
nextPublicToken: $NEXT_PUBLIC_TOKEN
providerId: '5159'
providerName: 'beachsidebiotech'
replicaCount: 1
scientistApiVersion: 'v2'
sentryAuthToken: $SENTRY_AUTH_TOKEN
sentryDsn: 'https://8e15464aee1fdfc31f70ed416c6bfdc9@o1008683.ingest.sentry.io/4506236741025792'
sentryOrg: 'scientist-inc'
sentryProject: 'webstore'
sentryUrl: 'https://sentry.io/'
webhookUrl: 'http://ss-mailer/webstore'

image:
  repository: ghcr.io/scientist-softserv/webstore
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: '0.0.2'

imagePullSecrets:
  - name: github

ingress:
  enabled: true
  className: 'nginx'
  annotations: {
    nginx.ingress.kubernetes.io/proxy-body-size: '0',
    cert-manager.io/cluster-issuer: letsencrypt-prod
  }
  hosts:
    - host: webstore.softserv.cloud
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - webstore.softserv.cloud
      secretName: softservcloud
